# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optical_sensor_gui.ui'
#
# Created: Wed Apr 11 18:43:07 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(549, 712)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.devicesTab = QtGui.QWidget()
        self.devicesTab.setObjectName(_fromUtf8("devicesTab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.devicesTab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.widget_1 = QtGui.QWidget(self.devicesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_1.sizePolicy().hasHeightForWidth())
        self.widget_1.setSizePolicy(sizePolicy)
        self.widget_1.setObjectName(_fromUtf8("widget_1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.widget_1)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Device Status", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.connectLineEdit = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectLineEdit.sizePolicy().hasHeightForWidth())
        self.connectLineEdit.setSizePolicy(sizePolicy)
        self.connectLineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.connectLineEdit.setObjectName(_fromUtf8("connectLineEdit"))
        self.horizontalLayout.addWidget(self.connectLineEdit)
        self.connectPushButton = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectPushButton.sizePolicy().hasHeightForWidth())
        self.connectPushButton.setSizePolicy(sizePolicy)
        self.connectPushButton.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.connectPushButton.setObjectName(_fromUtf8("connectPushButton"))
        self.horizontalLayout.addWidget(self.connectPushButton)
        spacerItem = QtGui.QSpacerItem(114, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_8.addWidget(self.widget_1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.tabWidget.addTab(self.devicesTab, _fromUtf8(""))
        self.singleChannelTab = QtGui.QWidget()
        self.singleChannelTab.setObjectName(_fromUtf8("singleChannelTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.singleChannelTab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.widget_10 = QtGui.QWidget(self.singleChannelTab)
        self.widget_10.setObjectName(_fromUtf8("widget_10"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget_10)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.groupBox = QtGui.QGroupBox(self.widget_10)
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Selected Device", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.singleChannelDeviceComboBox = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleChannelDeviceComboBox.sizePolicy().hasHeightForWidth())
        self.singleChannelDeviceComboBox.setSizePolicy(sizePolicy)
        self.singleChannelDeviceComboBox.setMinimumSize(QtCore.QSize(180, 0))
        self.singleChannelDeviceComboBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.singleChannelDeviceComboBox.setObjectName(_fromUtf8("singleChannelDeviceComboBox"))
        self.horizontalLayout_13.addWidget(self.singleChannelDeviceComboBox)
        spacerItem2 = QtGui.QSpacerItem(332, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.horizontalLayout_12.addWidget(self.groupBox)
        self.verticalLayout_7.addWidget(self.widget_10)
        self.line = QtGui.QFrame(self.singleChannelTab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_7.addWidget(self.line)
        self.widget_11 = QtGui.QWidget(self.singleChannelTab)
        self.widget_11.setObjectName(_fromUtf8("widget_11"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.widget_11)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.channelBox = QtGui.QGroupBox(self.widget_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelBox.sizePolicy().hasHeightForWidth())
        self.channelBox.setSizePolicy(sizePolicy)
        self.channelBox.setTitle(QtGui.QApplication.translate("MainWindow", "Selected Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.channelBox.setObjectName(_fromUtf8("channelBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.channelBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.channelRadioButton_1 = QtGui.QRadioButton(self.channelBox)
        self.channelRadioButton_1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.channelRadioButton_1.setObjectName(_fromUtf8("channelRadioButton_1"))
        self.horizontalLayout_3.addWidget(self.channelRadioButton_1)
        self.channelRadioButton_2 = QtGui.QRadioButton(self.channelBox)
        self.channelRadioButton_2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.channelRadioButton_2.setObjectName(_fromUtf8("channelRadioButton_2"))
        self.horizontalLayout_3.addWidget(self.channelRadioButton_2)
        self.channelRadioButton_3 = QtGui.QRadioButton(self.channelBox)
        self.channelRadioButton_3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.channelRadioButton_3.setObjectName(_fromUtf8("channelRadioButton_3"))
        self.horizontalLayout_3.addWidget(self.channelRadioButton_3)
        self.channelRadioButton_4 = QtGui.QRadioButton(self.channelBox)
        self.channelRadioButton_4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.channelRadioButton_4.setObjectName(_fromUtf8("channelRadioButton_4"))
        self.horizontalLayout_3.addWidget(self.channelRadioButton_4)
        self.channelRadioButton_5 = QtGui.QRadioButton(self.channelBox)
        self.channelRadioButton_5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.channelRadioButton_5.setObjectName(_fromUtf8("channelRadioButton_5"))
        self.horizontalLayout_3.addWidget(self.channelRadioButton_5)
        self.singleChannelStart = QtGui.QPushButton(self.channelBox)
        self.singleChannelStart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.singleChannelStart.setObjectName(_fromUtf8("singleChannelStart"))
        self.horizontalLayout_3.addWidget(self.singleChannelStart)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_14.addWidget(self.channelBox)
        self.verticalLayout_7.addWidget(self.widget_11)
        self.line_2 = QtGui.QFrame(self.singleChannelTab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_7.addWidget(self.line_2)
        self.widget_5 = QtGui.QWidget(self.singleChannelTab)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.singleChannelLevelBox = QtGui.QGroupBox(self.widget_5)
        self.singleChannelLevelBox.setTitle(QtGui.QApplication.translate("MainWindow", "Fluid Level", None, QtGui.QApplication.UnicodeUTF8))
        self.singleChannelLevelBox.setObjectName(_fromUtf8("singleChannelLevelBox"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.singleChannelLevelBox)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.singleChannelProgressBar = QtGui.QProgressBar(self.singleChannelLevelBox)
        self.singleChannelProgressBar.setProperty("value", 0)
        self.singleChannelProgressBar.setFormat(QtGui.QApplication.translate("MainWindow", "%v nl", None, QtGui.QApplication.UnicodeUTF8))
        self.singleChannelProgressBar.setObjectName(_fromUtf8("singleChannelProgressBar"))
        self.horizontalLayout_5.addWidget(self.singleChannelProgressBar)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_6.addWidget(self.singleChannelLevelBox)
        self.verticalLayout_7.addWidget(self.widget_5)
        self.line_3 = QtGui.QFrame(self.singleChannelTab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_7.addWidget(self.line_3)
        self.widget_4 = QtGui.QWidget(self.singleChannelTab)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.singleChannelPixelBox = QtGui.QGroupBox(self.widget_4)
        self.singleChannelPixelBox.setTitle(QtGui.QApplication.translate("MainWindow", "Pixel Values", None, QtGui.QApplication.UnicodeUTF8))
        self.singleChannelPixelBox.setObjectName(_fromUtf8("singleChannelPixelBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.singleChannelPixelBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.mpl = MplWidget(self.singleChannelPixelBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setMinimumSize(QtCore.QSize(250, 250))
        self.mpl.setObjectName(_fromUtf8("mpl"))
        self.verticalLayout_5.addWidget(self.mpl)
        self.verticalLayout_6.addWidget(self.singleChannelPixelBox)
        self.verticalLayout_7.addWidget(self.widget_4)
        self.tabWidget.addTab(self.singleChannelTab, _fromUtf8(""))
        self.multiChannelTab = QtGui.QWidget()
        self.multiChannelTab.setObjectName(_fromUtf8("multiChannelTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.multiChannelTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.widget_6 = QtGui.QWidget(self.multiChannelTab)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_6)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.multiChannelLevelBox = QtGui.QGroupBox(self.widget_6)
        self.multiChannelLevelBox.setTitle(QtGui.QApplication.translate("MainWindow", "Fluid Levels", None, QtGui.QApplication.UnicodeUTF8))
        self.multiChannelLevelBox.setObjectName(_fromUtf8("multiChannelLevelBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.multiChannelLevelBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget_2 = QtGui.QWidget(self.multiChannelLevelBox)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.logMultiChannel = QtGui.QPushButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logMultiChannel.sizePolicy().hasHeightForWidth())
        self.logMultiChannel.setSizePolicy(sizePolicy)
        self.logMultiChannel.setText(QtGui.QApplication.translate("MainWindow", "Log data", None, QtGui.QApplication.UnicodeUTF8))
        self.logMultiChannel.setObjectName(_fromUtf8("logMultiChannel"))
        self.horizontalLayout_4.addWidget(self.logMultiChannel)
        self.multiChannelStart = QtGui.QPushButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiChannelStart.sizePolicy().hasHeightForWidth())
        self.multiChannelStart.setSizePolicy(sizePolicy)
        self.multiChannelStart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.multiChannelStart.setObjectName(_fromUtf8("multiChannelStart"))
        self.horizontalLayout_4.addWidget(self.multiChannelStart)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout.addWidget(self.widget_2)
        self.scrollArea = QtGui.QScrollArea(self.multiChannelLevelBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 463, 486))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Device 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Ch 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.multiChannelProgressBar_1 = QtGui.QProgressBar(self.widget)
        self.multiChannelProgressBar_1.setProperty("value", 0)
        self.multiChannelProgressBar_1.setFormat(QtGui.QApplication.translate("MainWindow", "%v nl", None, QtGui.QApplication.UnicodeUTF8))
        self.multiChannelProgressBar_1.setObjectName(_fromUtf8("multiChannelProgressBar_1"))
        self.horizontalLayout_7.addWidget(self.multiChannelProgressBar_1)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_3 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_2 = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Ch 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.multiChannelProgressBar_2 = QtGui.QProgressBar(self.widget_3)
        self.multiChannelProgressBar_2.setProperty("value", 0)
        self.multiChannelProgressBar_2.setFormat(QtGui.QApplication.translate("MainWindow", "%v nl", None, QtGui.QApplication.UnicodeUTF8))
        self.multiChannelProgressBar_2.setObjectName(_fromUtf8("multiChannelProgressBar_2"))
        self.horizontalLayout_8.addWidget(self.multiChannelProgressBar_2)
        spacerItem9 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_7 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_4 = QtGui.QLabel(self.widget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Ch 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_9.addWidget(self.label_4)
        self.multiChannelProgressBar_3 = QtGui.QProgressBar(self.widget_7)
        self.multiChannelProgressBar_3.setProperty("value", 0)
        self.multiChannelProgressBar_3.setFormat(QtGui.QApplication.translate("MainWindow", "%v nl", None, QtGui.QApplication.UnicodeUTF8))
        self.multiChannelProgressBar_3.setObjectName(_fromUtf8("multiChannelProgressBar_3"))
        self.horizontalLayout_9.addWidget(self.multiChannelProgressBar_3)
        spacerItem10 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.widget_8 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_5 = QtGui.QLabel(self.widget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(50, 0))
        self.label_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Ch 4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_10.addWidget(self.label_5)
        self.multiChannelProgressBar_4 = QtGui.QProgressBar(self.widget_8)
        self.multiChannelProgressBar_4.setProperty("value", 0)
        self.multiChannelProgressBar_4.setFormat(QtGui.QApplication.translate("MainWindow", "%v nl", None, QtGui.QApplication.UnicodeUTF8))
        self.multiChannelProgressBar_4.setObjectName(_fromUtf8("multiChannelProgressBar_4"))
        self.horizontalLayout_10.addWidget(self.multiChannelProgressBar_4)
        spacerItem11 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.verticalLayout_2.addWidget(self.widget_8)
        self.widget_9 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widget_9)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_6 = QtGui.QLabel(self.widget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(50, 0))
        self.label_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Ch 5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_11.addWidget(self.label_6)
        self.multiChannelProgressBar_5 = QtGui.QProgressBar(self.widget_9)
        self.multiChannelProgressBar_5.setProperty("value", 0)
        self.multiChannelProgressBar_5.setFormat(QtGui.QApplication.translate("MainWindow", "%v nl", None, QtGui.QApplication.UnicodeUTF8))
        self.multiChannelProgressBar_5.setObjectName(_fromUtf8("multiChannelProgressBar_5"))
        self.horizontalLayout_11.addWidget(self.multiChannelProgressBar_5)
        spacerItem12 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.verticalLayout_2.addWidget(self.widget_9)
        spacerItem13 = QtGui.QSpacerItem(20, 206, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem13)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_3.addWidget(self.multiChannelLevelBox)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.tabWidget.addTab(self.multiChannelTab, _fromUtf8(""))
        self.verticalLayout_9.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.devicesTab), QtGui.QApplication.translate("MainWindow", "Devices", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.singleChannelTab), QtGui.QApplication.translate("MainWindow", "Single Channel Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.multiChannelTab), QtGui.QApplication.translate("MainWindow", "Multi Channel Mode", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import MplWidget
